### ISSUE TITLE
Formatting issues on iPhone (probably mobile in general)

### ISSUE THREAD

**Issue by arktn** [genshindev/web#8]
Hey I just saw that when opening https://genshin.dev on my iPhone the website shifts the "Follow us" and Discord text above the source code text block. Just a little bug I found, if you don't want to fix it I can fix it myself and just make a pull request. I added a screenshot down below so you can see it for yourself.
https://i.imgur.com/xWX0eBP.png

**Comment by NurMarvin** [comment]
I'm aware this happens on mobile platforms in general but I didn't really find a proper way to fix it when I initially re-built the page to this design. Feel free to open a PR with a fix because I've tried to fix it for multiple hours without success when I made the page.

**Comment by arktn** [comment]
Alright, if you couldn't fix it after multiple hours I don't even have to try, I'm not that great at front-end.
